development:
  adapter: mysql2
  database: library_development
  username: root
  password: "postgres"
  host: localhost

test:
  adapter: mysql2
  database: library_test
  username: root
  password: "postgres"
  host: localhost

production:
  adapter: mysql2
  database: library_production
  username: root
  password: "postgres"
  host: localhost
